// Code generated by Kitex v0.3.0. DO NOT EDIT.

package api

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/wannabea/OnlineJudge/oj_api/kitex_gen/announce"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetAnnouncementById(ctx context.Context, req *announce.AnnounceRequest, callOptions ...callopt.Option) (r *announce.AnnounceResponse, err error)
	GetAllAnnouncements(ctx context.Context, callOptions ...callopt.Option) (r []*announce.AnnounceResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kApiClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kApiClient struct {
	*kClient
}

func (p *kApiClient) GetAnnouncementById(ctx context.Context, req *announce.AnnounceRequest, callOptions ...callopt.Option) (r *announce.AnnounceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAnnouncementById(ctx, req)
}

func (p *kApiClient) GetAllAnnouncements(ctx context.Context, callOptions ...callopt.Option) (r []*announce.AnnounceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAllAnnouncements(ctx)
}
