// Code generated by Kitex v0.3.0. DO NOT EDIT.

package api

import (
	"github.com/cloudwego/kitex/server"
	"github.com/wannabea/OnlineJudge/announcement/kitex_gen/announce"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler announce.Api, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
