// Code generated by Kitex v0.3.0. DO NOT EDIT.

package api

import (
	"context"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	"oj_api/kitex_gen/api"
)

func serviceInfo() *kitex.ServiceInfo {
	return apiServiceInfo
}

var apiServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Api"
	handlerType := (*api.Api)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetAnnouncementById": kitex.NewMethodInfo(getAnnouncementByIdHandler, newApiGetAnnouncementByIdArgs, newApiGetAnnouncementByIdResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.3.0",
		Extra:           extra,
	}
	return svcInfo
}

func getAnnouncementByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ApiGetAnnouncementByIdArgs)
	realResult := result.(*api.ApiGetAnnouncementByIdResult)
	success, err := handler.(api.Api).GetAnnouncementById(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newApiGetAnnouncementByIdArgs() interface{} {
	return api.NewApiGetAnnouncementByIdArgs()
}

func newApiGetAnnouncementByIdResult() interface{} {
	return api.NewApiGetAnnouncementByIdResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetAnnouncementById(ctx context.Context, req *api.AnnounceRequest) (r *api.AnnounceResponse, err error) {
	var _args api.ApiGetAnnouncementByIdArgs
	_args.Req = req
	var _result api.ApiGetAnnouncementByIdResult
	if err = p.c.Call(ctx, "GetAnnouncementById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
