// Code generated by Kitex v0.3.0. DO NOT EDIT.

package api

import (
	"context"
	"github.com/OnlineJudge/announcement/kitex_gen/announcement"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return apiServiceInfo
}

var apiServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Api"
	handlerType := (*announcement.Api)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetAnnouncementById": kitex.NewMethodInfo(getAnnouncementByIdHandler, newApiGetAnnouncementByIdArgs, newApiGetAnnouncementByIdResult, false),
		"GetAllAnnouncements": kitex.NewMethodInfo(getAllAnnouncementsHandler, newApiGetAllAnnouncementsArgs, newApiGetAllAnnouncementsResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "announcement",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.3.0",
		Extra:           extra,
	}
	return svcInfo
}

func getAnnouncementByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*announcement.ApiGetAnnouncementByIdArgs)
	realResult := result.(*announcement.ApiGetAnnouncementByIdResult)
	success, err := handler.(announcement.Api).GetAnnouncementById(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newApiGetAnnouncementByIdArgs() interface{} {
	return announcement.NewApiGetAnnouncementByIdArgs()
}

func newApiGetAnnouncementByIdResult() interface{} {
	return announcement.NewApiGetAnnouncementByIdResult()
}

func getAllAnnouncementsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {

	realResult := result.(*announcement.ApiGetAllAnnouncementsResult)
	success, err := handler.(announcement.Api).GetAllAnnouncements(ctx)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newApiGetAllAnnouncementsArgs() interface{} {
	return announcement.NewApiGetAllAnnouncementsArgs()
}

func newApiGetAllAnnouncementsResult() interface{} {
	return announcement.NewApiGetAllAnnouncementsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetAnnouncementById(ctx context.Context, req *announcement.AnnounceRequest) (r *announcement.AnnounceResponse, err error) {
	var _args announcement.ApiGetAnnouncementByIdArgs
	_args.Req = req
	var _result announcement.ApiGetAnnouncementByIdResult
	if err = p.c.Call(ctx, "GetAnnouncementById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAllAnnouncements(ctx context.Context) (r []*announcement.AnnounceRequest, err error) {
	var _args announcement.ApiGetAllAnnouncementsArgs
	var _result announcement.ApiGetAllAnnouncementsResult
	if err = p.c.Call(ctx, "GetAllAnnouncements", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
