// Code generated by Kitex v0.3.0. DO NOT EDIT.

package user

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/wannabea/OnlineJudge/user/kitex_gen/user"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetNameById(ctx context.Context, userId int32, callOptions ...callopt.Option) (r string, err error)
	GetInfoById(ctx context.Context, userId int32, callOptions ...callopt.Option) (r *user.UserInfo, err error)
	InsertUser(ctx context.Context, info *user.InsertUserInfo, callOptions ...callopt.Option) (r int32, err error)
	UpdateUserInfo(ctx context.Context, info *user.InsertUserInfo, callOptions ...callopt.Option) (r int32, err error)
	CheckUserName(ctx context.Context, name string, callOptions ...callopt.Option) (r int32, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserClient struct {
	*kClient
}

func (p *kUserClient) GetNameById(ctx context.Context, userId int32, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNameById(ctx, userId)
}

func (p *kUserClient) GetInfoById(ctx context.Context, userId int32, callOptions ...callopt.Option) (r *user.UserInfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetInfoById(ctx, userId)
}

func (p *kUserClient) InsertUser(ctx context.Context, info *user.InsertUserInfo, callOptions ...callopt.Option) (r int32, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InsertUser(ctx, info)
}

func (p *kUserClient) UpdateUserInfo(ctx context.Context, info *user.InsertUserInfo, callOptions ...callopt.Option) (r int32, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserInfo(ctx, info)
}

func (p *kUserClient) CheckUserName(ctx context.Context, name string, callOptions ...callopt.Option) (r int32, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckUserName(ctx, name)
}
